### ISSUE TITLE
why using matmul in this line query_result = tf.matmul(normalized_keys, tf.transpose(normalized_query)) ??? and can i use another data set (numbers) ???

### ISSUE THREAD

**Issue by NeveenHijazi** [TDeVries/fast_knn_gpu#4]

**Comment by NeveenHijazi** [comment]
@TDeVries 
Hi , can you explane these lines?
x_keys = tf.placeholder("float", [None, 784])
x_queries = tf.placeholder("float", [None, 784])

normalized_keys = tf.nn.l2_normalize(x_keys, dim=1)
normalized_query = tf.nn.l2_normalize(x_queries, dim=1)
query_result = tf.matmul(normalized_keys, tf.transpose(normalized_query))
pred = tf.arg_max(query_result, dimension=0)
 thanks.

**Comment by TDeVries** [comment]
x_queries represents a sample (or multiple samples) that we want to find the nearest neighbour for.
x_keys represents the set of datapoints that we will be looking through in order to find that nearest neighbour.

In this case we will use cosine similarity (https://en.wikipedia.org/wiki/Cosine_similarity) to measure how close each datapoint is to each other. First we normalize all vectors so that they are similar magnitude (yielding normalized_keys and normalized_query), then we perform a matrix multiplication (i.e. dot product) between the key vectors and the query vectors (yielding query_result). Dot products between vectors that are more similar to each other will produce larger values, so by using arg_max we can find which vectors in x_keys were the closest for each vector in x_queries. 

Hope that helped!

**Comment by NeveenHijazi** [comment]
thx @TDeVries 
i have another question.
when i try to change the k value in knn i replace the  argmax with top K :

pred = tf.nn.top_k(query_result, k=5)
i get an error : 

IndexError: arrays used as indices must be of integer (or boolean) type
in this line:  accuracy = np.sum(Y_train[nn_index] == Y_test).astype(float) / len(Y_test)
any suggestions???
